---
- name: Configurating file hadoop-env.sh
  template:
    src: 'templates/hadoop-env.sh.j2'
    dest: '{{ hadoop_home }}/etc/hadoop/hadoop-env.sh'
    owner: "{{ hadoop_user }}"
    group: "{{ hadoop_user }}"
  become: yes

- name: Configurating file core-site.xml
  template:
    src: 'templates/core-site.xml.j2'
    dest: '{{ hadoop_home }}/etc/hadoop/core-site.xml'
    owner: "{{ hadoop_user }}"
    group: "{{ hadoop_user }}"
  become: yes

- name: Verfirying if DFS folder exists
  become: true
  stat:
    path: "{{ hadoop_home }}/{{ dfs_folder_home }}"
  register: dfs_folder

- name: Create DFS folder
  become: true
  file:
    path: "{{ hadoop_home }}/{{ dfs_folder_home }}"
    recurse: yes
    state: directory
    owner: "{{ hadoop_user }}"
    group: "{{ hadoop_user }}"
  when: dfs_folder.stat.exists == false

- name: Create DFS DATA folder
  become: true
  file:
    path: "{{ hadoop_home }}/{{ dfs_folder_home }}/data"
    recurse: yes
    state: directory
    owner: "{{ hadoop_user }}"
    group: "{{ hadoop_user }}"
  when: dfs_folder.stat.exists == false

- name: Create DFS LOG folder
  become: true
  file:
    path: "{{ hadoop_home }}/{{dfs_folder_home }}/namespace_logs"
    recurse: yes
    state: directory
    owner: "{{ hadoop_user }}"
    group: "{{ hadoop_user }}"
  when: dfs_folder.stat.exists == false

- name: Configurating file hdfs-site.xml
  template:
    src: 'templates/hdfs-site.xml.j2'
    dest: '{{ hadoop_home }}/etc/hadoop/hdfs-site.xml'
    owner: "{{ hadoop_user }}"
    group: "{{ hadoop_user }}"
  become: yes

- name: Configurating file workers
  template:
    src: 'templates/workers.j2'
    dest: '{{ hadoop_home }}/etc/hadoop/workers'
    owner: "{{ hadoop_user }}"
    group: "{{ hadoop_user }}"
  become: yes

- name: Configurating file mapred-site.xml
  template:
    src: 'templates/mapred-site.xml.j2'
    dest: '{{ hadoop_home }}/etc/hadoop/mapred-site.xml'
    owner: "{{ hadoop_user }}"
    group: "{{ hadoop_user }}"
  become: yes

- name: Configurating file yarn-site.xml.j2
  template:
    src: 'templates/yarn-site.xml.j2'
    dest: '{{ hadoop_home }}/etc/hadoop/yarn-site.xml'
    owner: "{{ hadoop_user }}"
    group: "{{ hadoop_user }}"
  become: yes
