---
- hosts: hdp_master
  roles:
    # - firewalld_disable
    - sshd_config
    - ssh_key_generate
    - ssh_key_install
    - hadoop_config
    - spark_install
    - hadoop_cluster_scripts

- hosts: hdp_node01
  roles:
    # - firewalld_disable
    - sshd_config
    - ssh_key_install
    - hadoop_config

- hosts: hdp_node02
  roles:
    # - firewalld_disable
    - sshd_config
    - ssh_key_install
    - hadoop_config
