---
- hosts: hdp_master
  roles:
    - sshd_config
    - ssh_key_generate
    - ssh_key_install
    - hadoop_config
    - spark_install
    - hadoop_cluster_scripts

- hosts: hdp_node01
  roles:
    - sshd_config
    - ssh_key_install
    - hadoop_config

- hosts: hdp_node02
  roles:
    - sshd_config
    - ssh_key_install
    - hadoop_config

- hosts: custumer_db
  roles:
    - mysql_install
    - custumer_db_config

- hosts: replication
  roles:
    - sshd_config
    - ssh_key_install
    - hadoop_config
    - sqoop_install
    - flume_install
    - nifi_install

- hosts: hive_server
  roles:
    - sshd_config
    - ssh_key_install
    - hive_install

- hosts: message_server
  roles:
    - sshd_config
    - ssh_key_install
    - hadoop_config
    - kafka_install
    - streamsets_install
