---
- hosts: hdp_master
  roles:
    - network
    - firewalld_disable
    - sshd_config
    - ssh_key_generate
    - ssh_key_install
    - hadoop_config
    - spark_install
    - hadoop_cluster_scripts

- hosts: hdp_node01
  roles:
    - network
    - firewalld_disable
    - sshd_config
    - ssh_key_install
    - hadoop_config

- hosts: hdp_node02
  roles:
    - network
    - firewalld_disable
    - sshd_config
    - ssh_key_install
    - hadoop_config

- hosts: custumer_db
  roles:
    - network
    - firewalld_disable
    - mysql_install
    - custumer_db_config

- hosts: replication
  roles:
    - network
    - firewalld_disable
    - sshd_config
    - ssh_key_install
    - hadoop_config
    - sqoop_install

- hosts: hive_server
  roles:
    - network
    - firewalld_disable
    - sshd_config
    - ssh_key_install
    - hive_install
