---
 - name: Copy hdp-key Private Key
   become: true
   copy:
     src: files/id_rsa
     dest: '/home/{{ hadoop_user }}/.ssh/{{ ssh_key_name }}'
     owner: "{{ hadoop_user }}"
     group: "{{ hadoop_user }}"
     mode: '0400'

 - name: Copy hdp-key Public Key
   become: true
   copy:
     src: files/id_rsa.pub
     dest: '/home/{{ hadoop_user }}/.ssh/{{ ssh_key_name }}.pub'
     owner: "{{ hadoop_user }}"
     group: "{{ hadoop_user }}"
     mode: '0400'
