---
- name: 'Install OpenJDK 8'
  yum:
    name: "java-1.8.0-openjdk-devel"
    state: present
  become: yes

- name: Define JAVA_HOME environment variable
  lineinfile:
    path: '/home/{{ hadoop_user }}/.bash_profile'
    state: present
    regexp: ^JAVA_HOME=
    line: "export JAVA_HOME={{ java_home }}"
  become: yes

- name: Define JAVA PATH on environment
  lineinfile:
    path: '/home/{{ hadoop_user }}/.bash_profile'
    state: present
    regexp: ^$PATH:$JAVA_HOME/bin=
    line: "export PATH=$PATH:$JAVA_HOME/bin"
  become: yes
