---
- name: Add Ansible inventory mappings to /etc/hosts
  become: true
  blockinfile:
    path: /etc/hosts
    block: |
      {% for host in groups['all'] %}
      {{ hostvars[host].host_ip }} {{ hostvars[host].host_name }}
      {% endfor %}

# - name: Disable localhost on /etc/hosts
#   become: true
#   lineinfile:
#     path: /etc/hosts
#     state: present
#     regexp: '127\.0\.0\.1      {{ host_name }}      {{ host_name }}'
#     line: "#127.0.0.1      {{ host_name }}      {{ host_name }}"
