---
- name: Add Ansible inventory mappings to /etc/hosts
  become: true
  blockinfile:
    path: /etc/hosts
    block: |
      {% for host in groups['all'] %}
      {{ hostvars[host].host_ip }} {{ hostvars[host].host_name }}
      {% endfor %}

- name: Stop and Disable Firewalld
  become: true
  service:
    name: firewalld
    state: stopped
    enabled: false
