---
  - name: Install PostgreSQL
    become: true
    yum:
      name: "{{ packages }}"
      state: present
    vars:
      packages:
        - postgresql
        - postgresql-server

  - name: Start PostgreSQL
    become: true
    service:
      name: postgresql.service
      state: started
      enabled: true
